language: java
jdk: oraclejdk8
script: mvn package
deploy:
  provider: releases
  api_key:
    secure: "JBz2PLRmUrN6p93fJFQdT02v/EUIv3lNfbQxopaXoXRZeRIbZcT7/WX8NXqUjGYa+qIf8U5/Fa+2jYpptUQR42xMv7ki6giCwnY8mBYDjGk9CFZMQtQqSCXLIuQsmowlP6W6f4tF7tkBkPwI0783bSselGGlPLM3+BoCNoDYshct1X84UDG8fWOBZ6Vj4irkYBoBA4a+IEucJ14G2GeB8X/GqlFeVxnIp9+l+Bt7nWcj9liZxb4PkARnuwTT83Q8YPEOmgOpr0xEmgkzegxp47AB1AA6kNDtrTZS8pSU81xZhZrDJhkH3a+JqpCLWMkX/7MTkHn/o5FTkKJIggLOoq3Q7RtBLR9r2NMxP5IEp33wAqQJae+L48NFwjcgpRAghMC0wCLsIwUdj29xBRob6uwwj5j/nPcdkPGi2/hDFqEMmKRpLq+Kbv/BuiSAcxD7n9+66YObDW4vkrwfdfom33uvOSAs0Dg17LcPXc9nRg0Pg/vjCjvHTv2zpGckkcnWXtZO9R8uuIcTTsDTDZB4E21DI5EIo5iQQKZr3hgAO2dhWctQrQKDkpmgZskdh2tLwtrdfhQ7rHMhoxj4Elwshg/xFGoRctooQd5TOYofUCu3B6S+khAwcOBMrmoqxgLUMMoDLdD8QJgywjMQgMJ25vUrPT+b0yJxx6bjqXTtjiE="
  file: 'Nickify.jar'
  skip_cleanup: true
  on:
    tags
cache:
  directories:
  - $HOME/.m2

